name: '🤖 Upstream Watcher'

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  check:
    uses: Lanrenbang/.github/.github/workflows/reusable-upstream-watcher.yml@main
    with:
      repositories: |
        [
          {"repo": "Lanrenbang/envwarp"},
          {"repo": "XTLS/Xray-core"},
          {"repo": "go-chi/chi"}
        ]
      go_mod_deps: |
        [
          {"repo": "XTLS/Xray-core", "module": "github.com/xtls/xray-core"},
          {"repo": "go-chi/chi", "module": "github.com/go-chi/chi/v5"}
        ]
    secrets:
      bot_pat: ${{ secrets.BOT_PAT }}
